[package]
name = "actixemdata"
version = "0.1.0"
authors = ["wangxiao <wx497657341@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.13"
redis = "0.20.1"